[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.3.0"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
dara-core = "=1.3.0"
plotly = ">=5.14.0, <5.15.0"
typing-extensions = ">=4.0.0, <4.6.0"
pandas = ">=1.1.0, <3.0.0"
dara-components = "=1.3.0"
croniter = "^1.0.15"
httpx = ">=0.23.0"
python = ">=3.8.0, <3.12.0"
responses = "^0.18.0"
pydantic = ">=1.8.1, <2.0.0"
exceptiongroup = "^1.1.3"
python-multipart = "^0.0.5"
pyxlsb = "*"
jinja2 = ">=2.1.1, <3.1.0"
odfpy = "*"
cryptography = ">=41.0.3"
anyio = ">=4.0.0"
cai-causal-graph = ">=0.1.0"
fastapi = ">=0.95.1, <0.96.0"
scipy = "*"
async-asgi-testclient = "^1.4.11"
pyarrow = "*"
fastapi-vite = "^0.3.1"
xlrd = "*"
prometheus-client = "^0.14.1"
python-dotenv = "^0.19.2"
colorama = "^0.4.6"
bokeh = ">=3.1.0, <3.2.0"
matplotlib = ">=2.0.0"
seaborn = ">=0.11.0"
cookiecutter = "^2.1.1"
packaging = "^23.1"
pyjwt = ">=2.0.1, <3.0.0"
click = "=8.1.3"
toml = "^0.10.2"
tblib = "^1.7.0"
openpyxl = "*"
dill = ">=0.3.0, <0.4.0"

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dependencies.create-dara-app]
version = "=1.3.0"
optional = true

[tool.poetry.dev-dependencies]
types-requests = "^2.28.1"
pylint-print = "^1.0.1"
types-croniter = "^1.0.10"
requests = ">=2.25.1, <3.0.0"
pytest-timeout = "^2.1.0"
mypy = "^0.991.0"
blue = "^0.9.0"
isort = "^5.10.1"
freezegun = "^1.2.2"
bandit = "^1.7.5"
pytest = "^7.0.0"
pylint = ">=2.6.0, <3.0.0"

[tool.poetry.dev-dependencies.decision-app]
path = "packages/decision-app"
develop = true

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true
[tool.borg.scripts]
