[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.1.2"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
pandas = ">=1.1.0, <3.0.0"
click = "=8.1.3"
pyxlsb = "*"
python = ">=3.8.0, <3.12.0"
fastapi = ">=0.95.1, <0.96.0"
fastapi-vite = "^0.3.1"
odfpy = "*"
jinja2 = ">=2.1.1, <3.1.0"
pydantic = ">=1.8.1, <2.0.0"
httpx = ">=0.23.0"
plotly = ">=5.14.0, <5.15.0"
toml = "^0.10.2"
tblib = "^1.7.0"
scipy = "*"
colorama = "^0.4.6"
dara-core = "=1.1.2"
prometheus-client = "^0.14.1"
pyarrow = "*"
dill = ">=0.3.0, <0.4.0"
seaborn = ">=0.11.0"
pyjwt = ">=2.0.1, <3.0.0"
python-multipart = "^0.0.5"
cryptography = ">=41.0.3"
openpyxl = "*"
async-asgi-testclient = "^1.4.11"
packaging = "^23.1"
python-dotenv = "^0.19.2"
cai-causal-graph = ">=0.1.0"
matplotlib = ">=2.0.0"
xlrd = "*"
responses = "^0.18.0"
typing-extensions = ">=4.0.0, <4.6.0"
cookiecutter = "^2.1.1"
bokeh = ">=3.1.0, <3.2.0"
croniter = "^1.0.15"

[tool.poetry.dependencies.dara-components]
version = "=1.1.2"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dependencies.create-dara-app]
version = "=1.1.2"
optional = true

[tool.poetry.dev-dependencies]
pytest-timeout = "^2.1.0"
types-croniter = "^1.0.10"
mypy = "^0.991.0"
pytest = "^7.4.1"
pylint = ">=2.6.0, <3.0.0"
requests = ">=2.25.1, <3.0.0"
bandit = "^1.7.5"
isort = "^5.10.1"
types-requests = "^2.28.1"
blue = "^0.9.0"

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true
[tool.borg.scripts]
