[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.0.0"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
fastapi-vite = "^0.3.1"
pyjwt = ">=2.0.1, <3.0.0"
bokeh = ">=3.1.0, <3.2.0"
plotly = ">=5.14.0, <5.15.0"
cookiecutter = "^2.1.1"
dill = ">=0.3.0, <0.4.0"
openpyxl = "*"
python-dotenv = "^0.19.2"
click = "=8.1.3"
pyxlsb = "*"
toml = "^0.10.2"
cai-causal-graph = ">=0.0.1"
seaborn = ">=0.11.0"
packaging = "^23.1"
dara-core = "=1.0.0"
python-multipart = "^0.0.5"
async-asgi-testclient = "^1.4.11"
odfpy = "*"
xlrd = "*"
matplotlib = ">=2.0.0"
pyarrow = "*"
pydantic = ">=1.8.1, <2.0.0"
pandas = ">=1.1.0, <3.0.0"
colorama = "^0.4.6"
prometheus-client = "^0.14.1"
python = ">=3.8.0, <3.12.0"
responses = "^0.18.0"
cryptography = ">=41.0.3"
typing-extensions = ">=4.0.0, <4.6.0"
croniter = "^1.0.15"
tblib = "^1.7.0"
jinja2 = ">=2.1.1, <3.1.0"
httpx = ">=0.23.0"
fastapi = ">=0.95.1, <0.96.0"
scipy = "*"

[tool.poetry.dependencies.create-dara-app]
version = "=1.0.0"
optional = true

[tool.poetry.dependencies.dara-components]
version = "=1.0.0"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dev-dependencies]
blue = "^0.9.0"
types-requests = "^2.28.1"
pytest-timeout = "^2.1.0"
pytest = "^7.0.0"
mypy = "^0.991.0"
types-croniter = "^1.0.10"
pylint = ">=2.6.0, <3.0.0"
requests = ">=2.25.1, <3.0.0"
isort = "^5.10.1"
bandit = "^1.7.5"

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true
[tool.borg.scripts]
