[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.6.1"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
python-dotenv = ">=0.19.2"
odfpy = "*"
pydantic = ">=1.8.1, <2.0.0"
prometheus-client = "^0.14.1"
pandas = ">=1.1.0, <3.0.0"
python-multipart = "^0.0.5"
click = "=8.1.3"
colorama = "^0.4.6"
async-asgi-testclient = "^1.4.11"
pyjwt = ">=2.0.1, <3.0.0"
httpx = ">=0.23.0"
matplotlib = ">=2.0.0"
pyxlsb = "*"
seaborn = ">=0.11.0"
pyarrow = "*"
python = ">=3.8.0, <3.12.0"
croniter = "^1.0.15"
toml = "^0.10.2"
openpyxl = "*"
fastapi = ">=0.95.1, <0.96.0"
anyio = ">=4.0.0"
cryptography = ">=41.0.3"
scipy = "*"
exceptiongroup = "^1.1.3"
jinja2 = ">=2.1.1, <3.1.0"
responses = "^0.18.0"
bokeh = ">=3.1.0, <3.2.0"
cookiecutter = "^2.1.1"
tblib = "^1.7.0"
plotly = ">=5.14.0, <5.15.0"
fastapi-vite = "^0.3.1"
dara-core = "=1.6.1"
dill = ">=0.3.0, <0.4.0"
packaging = "^23.1"
xlrd = "*"
cai-causal-graph = ">=0.3.6"
typing-extensions = ">=4.5.0"

[tool.poetry.dependencies.create-dara-app]
version = "=1.6.1"
optional = true

[tool.poetry.dependencies.dara-components]
version = "=1.6.1"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
mypy = "^1.6.0"
bandit = "^1.7.5"
freezegun = "^1.2.2"
types-requests = "^2.28.1"
pytest = "^7.0.0"
blue = "^0.9.0"
pylint = "^3.0.0"
types-croniter = "^1.0.10"
pytest-timeout = "^2.1.0"
requests = ">=2.25.1, <3.0.0"

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true
[tool.borg.scripts]
