[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.2.3"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
bokeh = ">=3.1.0, <3.2.0"
colorama = "^0.4.6"
xlrd = "*"
dill = ">=0.3.0, <0.4.0"
croniter = "^1.0.15"
httpx = ">=0.23.0"
scipy = "*"
async-asgi-testclient = "^1.4.11"
plotly = ">=5.14.0, <5.15.0"
seaborn = ">=0.11.0"
cryptography = ">=41.0.3"
pyxlsb = "*"
pyarrow = "*"
packaging = "^23.1"
exceptiongroup = "^1.1.3"
matplotlib = ">=2.0.0"
anyio = ">=4.0.0"
click = "=8.1.3"
jinja2 = ">=2.1.1, <3.1.0"
cai-causal-graph = ">=0.1.0"
dara-core = "=1.2.3"
pandas = ">=1.1.0, <3.0.0"
tblib = "^1.7.0"
prometheus-client = "^0.14.1"
fastapi = ">=0.95.1, <0.96.0"
typing-extensions = ">=4.0.0, <4.6.0"
openpyxl = "*"
odfpy = "*"
python-multipart = "^0.0.5"
cookiecutter = "^2.1.1"
pydantic = ">=1.8.1, <2.0.0"
fastapi-vite = "^0.3.1"
pyjwt = ">=2.0.1, <3.0.0"
toml = "^0.10.2"
python-dotenv = "^0.19.2"
responses = "^0.18.0"
python = ">=3.8.0, <3.12.0"

[tool.poetry.dependencies.dara-components]
version = "=1.2.3"
optional = true

[tool.poetry.dependencies.create-dara-app]
version = "=1.2.3"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dev-dependencies]
blue = "^0.9.0"
types-requests = "^2.28.1"
bandit = "^1.7.5"
isort = "^5.10.1"
requests = ">=2.25.1, <3.0.0"
types-croniter = "^1.0.10"
mypy = "^0.991.0"
pylint-print = "^1.0.1"
pylint = ">=2.6.0, <3.0.0"
pytest = "^7.0.0"
pytest-timeout = "^2.1.0"
freezegun = "^1.2.2"

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true
[tool.borg.scripts]
