[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.8.2"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
anyio = ">=4.0.0"
exceptiongroup = "^1.1.3"
dara-core = "=1.8.2"
pandas = ">=1.1.0, <3.0.0"
pyarrow = "*"
bokeh = ">=3.1.0, <3.2.0"
tblib = "^1.7.0"
python-dotenv = ">=0.19.2"
click = "=8.1.3"
typing-extensions = ">=4.5.0"
odfpy = "*"
toml = "^0.10.2"
openpyxl = "*"
pydantic = ">=1.8.1, <2.0.0"
async-asgi-testclient = "^1.4.11"
scipy = "*"
prometheus-client = "^0.14.1"
responses = "^0.18.0"
python-multipart = "^0.0.7"
cryptography = ">=42.0.4"
seaborn = ">=0.11.0"
croniter = "^1.0.15"
pyjwt = ">=2.0.1, <3.0.0"
fastapi-vite = "^0.3.1"
cookiecutter = "^2.1.1"
aiorwlock = "^1.4.0"
pyxlsb = "*"
xlrd = "*"
colorama = "^0.4.6"
jinja2 = ">=2.1.1, <3.1.0"
python = ">=3.8.0, <3.12.0"
dill = ">=0.3.0, <0.4.0"
fastapi = "^0.109.0"
matplotlib = ">=2.0.0"
httpx = ">=0.23.0"
packaging = "^23.1"
cai-causal-graph = ">=0.3.6"
plotly = ">=5.14.0, <5.15.0"

[tool.poetry.dependencies.dara-components]
version = "=1.8.2"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dependencies.create-dara-app]
version = "=1.8.2"
optional = true

[tool.poetry.dev-dependencies]
requests = ">=2.25.1, <3.0.0"
isort = "^5.10.1"
bandit = "^1.7.5"
types-croniter = "^1.0.10"
freezegun = "^1.2.2"
pytest = "^7.0.0"
types-requests = "^2.28.1"
mypy = "^1.6.0"
blue = "^0.9.0"
pylint = "^3.0.0"
pytest-timeout = "^2.1.0"

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true
[tool.borg.scripts]
