[build-system]
requires = ["poetry"]
[tool.poetry]
name = "anthology-meta-package"
version = "1.10.4"
description = "Anthology Meta Package"
authors = ["anthology"]

[tool.poetry.dependencies]
aiorwlock = "^1.4.0"
cookiecutter = "^2.1.1"
prometheus-client = "^0.14.1"
exceptiongroup = "^1.1.3"
python = ">=3.8.0, <3.12.0"
python-multipart = "^0.0.7"
cai-causal-graph = ">=0.3.6"
click = "=8.1.3"
xlrd = "*"
pydantic = ">=1.8.1, <2.0.0"
pyarrow = "*"
toml = "^0.10.2"
httpx = ">=0.23.0"
fastapi = "^0.109.0"
responses = "^0.18.0"
dill = ">=0.3.0, <0.4.0"
bokeh = ">=3.1.0, <3.2.0"
matplotlib = ">=2.0.0"
anyio = ">=4.0.0"
python-dotenv = ">=0.19.2"
typing-extensions = ">=4.5.0"
pyxlsb = "*"
seaborn = ">=0.11.0"
odfpy = "*"
fastapi-vite = "^0.3.1"
async-asgi-testclient = "^1.4.11"
pyjwt = ">=2.0.1, <3.0.0"
jinja2 = ">=2.1.1, <3.1.0"
pandas = ">=1.1.0, <3.0.0"
dara-core = "=1.10.4"
scipy = "*"
cryptography = ">=42.0.4"
packaging = "^23.1"
colorama = "^0.4.6"
tblib = "^1.7.0"
croniter = "^1.0.15"
plotly = ">=5.14.0, <5.15.0"
openpyxl = "*"

[tool.poetry.dependencies.create-dara-app]
version = "=1.10.4"
optional = true

[tool.poetry.dependencies.dara-components]
version = "=1.10.4"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dev-dependencies]
blue = "^0.9.1"
pytest = "^7.0.0"
pytest-timeout = "^2.1.0"
isort = "^5.10.1"
pylint = "3.2.3"
requests = ">=2.25.1, <3.0.0"
bandit = "^1.7.5"
types-requests = "^2.28.1"
mypy = "^1.6.0"
freezegun = "^1.2.2"
types-croniter = "^1.0.10"

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true

[[tool.poetry.source]]
name = "causalens"
url = "https://us-central1-python.pkg.dev/causalens-internal/python-internal/simple"
priority = "supplemental"

[tool.anthology.scripts]
