[build-system]
requires = ["poetry"]
[tool.poetry]
name = "borg-meta-package"
version = "1.9.0"
description = "Borg Meta Package"
authors = ["borg"]

[tool.poetry.dependencies]
typing-extensions = ">=4.5.0"
pyarrow = "*"
aiorwlock = "^1.4.0"
bokeh = ">=3.1.0, <3.2.0"
dara-core = "=1.9.0"
click = "=8.1.3"
httpx = ">=0.23.0"
pydantic = ">=1.8.1, <2.0.0"
pyxlsb = "*"
cryptography = ">=42.0.4"
pandas = ">=1.1.0, <3.0.0"
scipy = "*"
jinja2 = ">=2.1.1, <3.1.0"
xlrd = "*"
fastapi-vite = "^0.3.1"
colorama = "^0.4.6"
matplotlib = ">=2.0.0"
async-asgi-testclient = "^1.4.11"
python-dotenv = ">=0.19.2"
croniter = "^1.0.15"
cai-causal-graph = ">=0.3.6"
tblib = "^1.7.0"
anyio = ">=4.0.0"
python = ">=3.8.0, <3.12.0"
seaborn = ">=0.11.0"
packaging = "^23.1"
odfpy = "*"
pyjwt = ">=2.0.1, <3.0.0"
responses = "^0.18.0"
plotly = ">=5.14.0, <5.15.0"
toml = "^0.10.2"
prometheus-client = "^0.14.1"
cookiecutter = "^2.1.1"
exceptiongroup = "^1.1.3"
python-multipart = "^0.0.7"
openpyxl = "*"
dill = ">=0.3.0, <0.4.0"
fastapi = "^0.109.0"

[tool.poetry.dependencies.dara-components]
version = "=1.9.0"
optional = true

[tool.poetry.dependencies.uvicorn]
version = "^0.22.0"

[tool.poetry.dependencies.create-dara-app]
version = "=1.9.0"
optional = true

[tool.poetry.dev-dependencies]
types-requests = "^2.28.1"
types-croniter = "^1.0.10"
isort = "^5.10.1"
pytest-timeout = "^2.1.0"
requests = ">=2.25.1, <3.0.0"
freezegun = "^1.2.2"
bandit = "^1.7.5"
pylint = "^3.0.0"
blue = "^0.9.0"
pytest = "^7.0.0"
mypy = "^1.6.0"

[tool.poetry.dev-dependencies.dara-components]
path = "packages/dara-components"
develop = true

[tool.poetry.dev-dependencies.dara-core]
path = "packages/dara-core"
develop = true

[tool.poetry.dev-dependencies.create-dara-app]
path = "packages/create-dara-app"
develop = true
[tool.borg.scripts]
