[build-system]
requires = ["poetry"]

[tool.poetry]
name = "dara-framework-monorepo"
version = "0.0.1"
description = "Dara Framework monorepo metapackage"
authors = ["causaLens <support@causalens.com>"]

[tool.poetry.dependencies]
python = ">=3.8.0, <3.12.0"

[tool.poetry.group.dev.dependencies]
dara-core = {path = "packages/dara-core", develop = true}
dara-components = {path = "packages/dara-components", develop = true}

