[tool.poetry]
name = "dara-components"
version = "0.0.1"
description = "Dara Framework Components"
authors = ["causaLens <support@causalens.com>"]
readme = "README.md"
packages = [{include = "dara"}]

[tool.poetry.dependencies]
python = ">=3.8.0, <3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dara-components = 'dara.components.main:main'
