name: Prace.js
on:
  pull_request:
    types:
      [
        "opened",
        "edited",
        "reopened",
        "synchronize",
        "review_requested",
        "review_request_removed",
        "assigned",
        "unassigned",
        "labeled",
        "unlabeled",
      ]

jobs:
  linting:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'dependabot/')"
    steps:
      - name: Print github.head_ref
        run: echo "Head ref is ${{ github.head_ref }}"
      - uses: innerspacetrainings/Prace.js@master
        with:
          configuration-path: .github/prace.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
