[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
[tool.blue]
line-length = 120
[tool.borg.scripts]

[tool.isort]
known_dara = ["dara"]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DARA", "FIRSTPARTY", "LOCALFOLDER"]

[tool.poetry]
authors = ["Author <author@example.com>"]
description = "Decision App"
name = "decision_app"
version = "1.1.11"

[tool.poetry.dependencies]
dara-components = "=1.1.11"
dara-core = "=1.1.11"
python = ">=3.8.0, <3.12.0"

[tool.poetry.dev-dependencies]
blue = "^0.9.0"
isort = "^5.10.1"

[tool.poetry.dev-dependencies.dara-components]
path = "../dara-components"

[tool.poetry.dev-dependencies.dara-core]
develop = true
path = "../dara-core"
